// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARD0JWg9VGBPptm7AZWKJ6Kkr8Gd_A_io',
    appId: '1:902645849846:web:133d7cbbcab0f00b2496d7',
    messagingSenderId: '902645849846',
    projectId: 'workers-tasks',
    authDomain: 'workers-tasks.firebaseapp.com',
    storageBucket: 'workers-tasks.appspot.com',
    measurementId: 'G-W20MLKDBC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiR8HoreLDo34tJUcyVcpUQnDmU3YpqFc',
    appId: '1:902645849846:android:b2ee64ffb62a76582496d7',
    messagingSenderId: '902645849846',
    projectId: 'workers-tasks',
    storageBucket: 'workers-tasks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC34FcBu-BX_-J_PZLcZMCGjdtWNThpjEc',
    appId: '1:902645849846:ios:6c1d705aedb03d432496d7',
    messagingSenderId: '902645849846',
    projectId: 'workers-tasks',
    storageBucket: 'workers-tasks.appspot.com',
    iosClientId: '902645849846-6d56fmhmhq4s1a883oe74lcdp1nmffn7.apps.googleusercontent.com',
    iosBundleId: 'com.example.workersTasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC34FcBu-BX_-J_PZLcZMCGjdtWNThpjEc',
    appId: '1:902645849846:ios:6c1d705aedb03d432496d7',
    messagingSenderId: '902645849846',
    projectId: 'workers-tasks',
    storageBucket: 'workers-tasks.appspot.com',
    iosClientId: '902645849846-6d56fmhmhq4s1a883oe74lcdp1nmffn7.apps.googleusercontent.com',
    iosBundleId: 'com.example.workersTasks',
  );
}
